### ISSUE TITLE
Feature: Lua interactive code snippets with wasm_lua and Klipse 

### ISSUE THREAD

**Issue by viebel** [vvanders/wasm_lua#2]
Hi there!

Amazing work of porting lua to wasm.

Lua is now supported by Klipse and we can have a blog post with interactive lua code snippets: Take a look here: http://blog.klipse.tech/lua/2017/03/19/blog-lua.html

**Comment by viebel** [comment]
@vvanders Could you describe the process of porting c/c++ code to wasm?

**Comment by vvanders** [comment]
That's a bit outside of the scope of this project, I'm sure you can find a bunch of resources on the emscripten website however.
